Agregando campos faltantes al Registro de empresa
leandroj1/ProyectoFinalPOO pull request #21
Opened 2022-07-28 15:35 UTC by Brigibel12

Hey este PR es para evaluar si a nivel visual no le falta nada a Registro de Empresa y si se ve bien.

2022-07-28 15:35 UTC, Brigibel12 commented
![image](https://user-images.githubusercontent.com/97652118/181578811-1f14eab7-abcf-4dd7-9101-0e5668baab1f.png)

2022-07-28 15:42 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegEmpresa.java
> +			comboBox.setModel(new DefaultComboBoxModel(new String[] {"<Seleccione>", "Industrial", "Agricultura ", "Alimentaci\u00F3n", "Comercio ", "Construcci\u00F3n", "Educaci\u00F3n ", "Hoteler\u00EDa", "
```suggestion
			comboBox.setModel(new DefaultComboBoxModel(new String[] {"<Seleccione>", "Industrial", "Agricultura", "Alimentaci\u00F3n", "Comercio", "Construcci\u00F3n", "Educaci\u00F3n", "Hoteler\u00EDa", "Medios de comunicaci\u00F3n", "Miner\u00EDa", "Petrolero", "Telecomunicaciones", "Salud", "Financieros", "P\u00FAblico", "Silvicultura", "Textil", "Tecnol\u00F3gico", "Transporte"}));

```

Hay espacios en los datos.

2022-07-28 15:51 UTC, leandroj1 commented
> ![image](https://user-images.githubusercontent.com/97652118/181578811-1f14eab7-abcf-4dd7-9101-0e5668baab1f.png)

Razón social debería estar más "_cerca_" del nombre comercial. Si decides mover razón social, considera también mover en conjunto a sector y rubro, es decir, ponerlos _cerca_ también.

2022-07-29 03:05 UTC, JeanLuisJimenez approved these changes

2022-07-29 03:38 UTC, leandroj1 requested changes

2022-07-29 03:38 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegEmpresa.java
> +				cbxCargoContacto.setModel(new DefaultComboBoxModel(new String[] {"<Seleccione>", "CEO", "CTO", "RRHH", "Secretario/a del CEO"}));
Se pueden agregar más cargos.

2022-07-29 03:39 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegEmpresa.java
> +				cbxCargoContacto.setModel(new DefaultComboBoxModel(new String[] {"<Seleccione>", "CEO", "CTO", "RRHH", "Secretario/a del CEO"}));
- Gerente de Logística
- Gerente de Comunicaciones
- Gerente de Operaciones
- Gerente de Servicios Administrativos

2022-07-29 03:40 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegEmpresa.java
> +				cbxCargoContacto.setModel(new DefaultComboBoxModel(new String[] {"<Seleccione>", "CEO", "CTO", "RRHH", "Secretario/a del CEO"}));
También se puede agregar la opción "Otro", en caso de no se encuentre listado.

2022-07-29 03:48 UTC, leandroj1 approved these changes

2022-07-29 03:48 UTC, merged