Empresa
leandroj1/ProyectoFinalPOO pull request #27
Opened 2022-07-30 12:12 UTC by Brigibel12

Este PR incluye el funcionamiento de registrar y listar empresa con sus validaciones de lugar.

2022-07-30 12:41 UTC, leandroj1 requested changes

2022-07-30 12:41 UTC, leandroj1 commented on ProyectoFinal/src/logico/BolsaTrabajo.java
> +	public Empresa buscarEmpresaByRNC(String codEmpresa) {
Ese método no es necesario. Puedes usar `getEmpresasByID(String RNC)`, y evalúas si el resultado de ese método tiene un `size` mayor que 0, y el objeto empresa sería `Empresa obj = resultado.get(0);`

2022-07-30 12:41 UTC, leandroj1 commented on ProyectoFinal/src/visual/ListarEmpresas.java
> +						JOptionPane.showMessageDialog(null, "Tiene que completar la c�dula", "Advertencia", JOptionPane.WARNING_MESSAGE);
```suggestion
						JOptionPane.showMessageDialog(null, "Tiene que completar la c\u00e9dula.", "Advertencia", JOptionPane.WARNING_MESSAGE);
```

Para que no de un símbolo extraño por el _encoding_.

2022-07-30 12:41 UTC, leandroj1 commented on ProyectoFinal/src/visual/ListarEmpresas.java
>  						setButtonsState(false);
```suggestion
						setButtonsState(false);
						selectedEmpresa = null;
```

Es bueno también reiniciar el objeto de `Empresa`.

2022-07-30 12:41 UTC, leandroj1 commented on ProyectoFinal/src/visual/ListarEmpresas.java
> +					setButtonsState(false);
```suggestion
					setButtonsState(false);
					selectedEmpresa = null;
```
Lo mismo.

2022-07-30 12:41 UTC, leandroj1 commented on ProyectoFinal/src/visual/ListarEmpresas.java
> +					setButtonsState(false);
```suggestion
					setButtonsState(false);
					selectedEmpresa = null;
```
Lo mismo.

2022-07-30 12:41 UTC, leandroj1 commented on ProyectoFinal/src/visual/ListarEmpresas.java
> +			model.setRowCount(0);
Puede ir fuera de los condicional, ya que se repite en el `if` y `else`.

2022-07-30 12:41 UTC, leandroj1 commented on ProyectoFinal/src/visual/ListarEmpresas.java
> +				row[0] = empresa.getRNC();
Para evitar el _copy-paste_, puedes crear un método llamado `getRowDataEmpresa(Empresa empresa)`, donde le pases la empresa y te retorne el objeto `row` y lo agregues al modelo.

Por lo que, si aplicas este cambio, también tendrías que quitar `row = new Object[model.getColumnCount()];` del inicio del método `loadRowsInTable(ArrayList<Empresa> empresas, Empresa e1)`.

2022-07-30 12:41 UTC, leandroj1 commented on ProyectoFinal/src/visual/ListarEmpresas.java
> +				row[0] = empresa.getRNC();
Solo tendrías que llamar el método para crear el row con los datos de la empresa y evaluar si no null, y luego agregarlo al modelo.

2022-07-30 12:41 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegEmpresa.java
> +			setTitle("Modificar Empresa");
```suggestion
			setTitle("Modificar datos de la empresa " + auxEmpresa.getNombreComercial());

```

Para mostrar información relevante en el título de la ventana.

2022-07-30 12:41 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegEmpresa.java
> +				cbxTipo.setModel(new DefaultComboBoxModel(new String[] {"<Seleccione>", "Micro", "Mediana", "Peque\u00F1a ", "Grande", "Emergente"}));
```suggestion
				cbxTipo.setModel(new DefaultComboBoxModel(new String[] {"<Seleccione>", "Micro", "Mediana", "Peque\u00F1a", "Grande", "Emergente"}));

```
Tenía un espacio.

2022-07-30 12:41 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegEmpresa.java
> +				cbxSector.setModel(new DefaultComboBoxModel(new String[] {"<Seleccione>", "Industrial", "Agricultura ", "Alimentaci\u00F3n", "Comercio ", "Construcci\u00F3n", "Educaci\u00F3n ", "Hoteler\u00EDa",
```suggestion
				cbxSector.setModel(new DefaultComboBoxModel(new String[] {"<Seleccione>", "Industrial", "Agricultura", "Alimentaci\u00F3n", "Comercio", "Construcci\u00F3n", "Educaci\u00F3n", "Hoteler\u00EDa", "Medios de comunicaci\u00F3n", "Miner\u00EDa", "Petrolero", "Telecomunicaciones", "Salud", "Financieros", "P\u00FAblico", "Silvicultura", "Textil", "Tecnol\u00F3gico", "Transporte"}));

```

Los datos tenían espacios, esto puede ser problemático en las comparaciones.

2022-07-30 12:41 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegEmpresa.java
> +										JOptionPane.showMessageDialog(null, "Registro exitoso", "Informacion", JOptionPane.INFORMATION_MESSAGE);
```suggestion
										JOptionPane.showMessageDialog(null, "Registro exitoso.", "Informaci\u00f3n", JOptionPane.INFORMATION_MESSAGE);

```

2022-07-30 14:31 UTC, leandroj1 approved these changes

2022-08-01 19:40 UTC, JeanLuisJimenez approved these changes

2022-08-01 20:15 UTC, merged