Feature/adding functionality to personal screens
leandroj1/ProyectoFinalPOO pull request #29
Opened 2022-07-31 04:58 UTC by JeanLuisJimenez

2022-07-31 12:18 UTC, leandroj1 requested changes

2022-07-31 12:18 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegSolPersonal.java
> +								int agnosExperiencia = (int) spnAgnosExp.getValue();
Usa `Utils.getSpinnerIntValue()`, por lo menos a mi, a veces me da error ese _casting_.

2022-07-31 12:18 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegSolPersonal.java
> +		idiomas.add("Ingles");
?

2022-07-31 12:18 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegSolPersonal.java
> +								if (JOptionPane.showConfirmDialog(null, "Quiere hacer otra solicitud?", null,
En el caso de que sea la primera solicitud de un personal (cuando se registra por primera vez), no debería aparecer este mensaje.

2022-07-31 12:18 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegSolPersonal.java
> +		if (txtFCedulaP.getText().equals(Utils.getMaskCedula().getMask().replace('#', '_')))
Hay funciones en `Utils` que te dicen si esos campos están en su valor por defecto.

2022-07-31 12:18 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegPersonal.java
> +						"Programaci\u00F3n Web", "" }));
```suggestion
						"Programaci\u00F3n Web"}));

```

2022-07-31 12:18 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegPersonal.java
> +							JOptionPane.showMessageDialog(null, "No se ha podido registrar el usuario");
Es mejor que sea un mensaje de tipo error.

2022-08-01 01:05 UTC, leandroj1 requested changes

2022-08-01 01:05 UTC, leandroj1 commented on ProyectoFinal/src/visual/RegSolPersonal.java
> +									JOptionPane.showMessageDialog(null, message);
Debería ser un mensaje de error.

2022-08-01 04:34 UTC, JeanLuisJimenez commented on ProyectoFinal/src/logico/BolsaTrabajo.java
> +		if (empresa != null && getPersonalByID(empresa.getRNC()).size() == 0)
Validar que no agrego un duplicado, en base al RNC

2022-08-01 05:27 UTC, JeanLuisJimenez commented on ProyectoFinal/src/visual/RegSolPersonal.java
> +		idiomas.add("Ingles");
Eso era para un test, lo estoy quitando

2022-08-01 05:30 UTC, JeanLuisJimenez commented on ProyectoFinal/src/visual/Principal.java
>  				solPersonal.setVisible(true);
por default ya es un modal, no hay necesidad de especificarlo aqui

2022-08-01 05:31 UTC, JeanLuisJimenez commented on ProyectoFinal/src/visual/RegSolPersonal.java
> +		idiomas.add("Ingles");
Leftover

2022-08-01 05:32 UTC, JeanLuisJimenez commented on ProyectoFinal/src/visual/RegSolPersonal.java
> +								if (JOptionPane.showConfirmDialog(null, "Quiere hacer otra solicitud?", null,
Porque no? Y si el usuario viene para hacer mas de una solicitud, aunque se haya registrado por primera vez?

2022-08-01 21:33 UTC, leandroj1 approved these changes

2022-08-01 23:54 UTC, Brigibel12 approved these changes

2022-08-02 01:30 UTC, merged