Feature/listado peronal y solicitud
leandroj1/ProyectoFinalPOO pull request #36
Opened 2022-08-07 03:02 UTC by JeanLuisJimenez

2022-08-07 08:59 UTC, Brigibel12 requested changes

2022-08-07 08:59 UTC, Brigibel12 commented on ProyectoFinal/src/visual/ListarPersonal.java
> +		/* Data de prueba, borrar antes de hacer merge */
Eliminar antes de hacer merge

2022-08-07 12:23 UTC, leandroj1 requested changes
**Cambios necesarios:**
Interfaz de ver detalles de personal:
- Los datos del tipo de trabajador no cargan

Interfaz de modificar personal:
- No cargan los datos de tipo de trabajador
- Los datos de tipo de trabajar no se deberían de modificar
- La fecha de nacimiento no se debería de modificar

Interfaz de listado de personal:
- No se debería cambiar el tipo de personal con el que se hace la solicitud ni los datos asociados a el (para eso se tendría que crear una nueva solicitud y anular la otra)

2022-08-07 18:35 UTC, leandroj1 commented
![image](https://user-images.githubusercontent.com/98528793/183305837-f020aaa9-3517-48bd-bcf9-4cfd7124066f.png)
En ver detalles de solicitud de personal no debería salir el botón de solicitar.

![image](https://user-images.githubusercontent.com/98528793/183305874-d19ac084-9266-481f-8fe8-c2e29e13161a.png)
Cuando le doy a modificar solicitud de personal, no debería preguntarme si quiero crear otra solicitud.

2022-08-07 20:49 UTC, leandroj1 commented
Cuando se crea un nuevo personal y termino de crear su solicitud (se cierra crear solicitud personal), no se limpian los datos de crear personal.

2022-08-07 20:50 UTC, leandroj1 commented
Crear personal no valida si la cedula existe antes de pasar a la pantalla de crear solicitud personal.

2022-08-07 20:51 UTC, leandroj1 commented
> Cuando se crea un nuevo personal y termino de crear su solicitud (se cierra crear solicitud personal), no se limpian los datos de crear personal.

Ni siquiera se registra el personal.

2022-08-07 22:18 UTC, leandroj1 commented
![image](https://user-images.githubusercontent.com/98528793/183313165-9c6996e3-ba89-45c2-b305-17a69fb5ab79.png)
![image](https://user-images.githubusercontent.com/98528793/183313172-1b48dd69-3b39-48a8-ac4b-84b6b9061fc5.png)

2022-08-07 22:20 UTC, leandroj1 commented
![image](https://user-images.githubusercontent.com/98528793/183313217-d10ac188-1dcf-41f4-b94d-9c549edeeb38.png)
Y ese botón?

2022-08-07 22:20 UTC, leandroj1 commented
![image](https://user-images.githubusercontent.com/98528793/183313228-46d17dab-f007-4eaf-891c-0fa8c4e2c6b1.png)
No debería ser creado. No tendría que crearlo y tendría que decir algo como "Ya existe una persona con esa cédula registrada."

2022-08-07 22:20 UTC, JeanLuisJimenez commented
> ![image](https://user-images.githubusercontent.com/98528793/183313217-d10ac188-1dcf-41f4-b94d-9c549edeeb38.png) Y ese botón?

My bad, era para testear la funcion clear sin tener que llenar todo XD

2022-08-07 22:24 UTC, leandroj1 commented
![image](https://user-images.githubusercontent.com/98528793/183313295-09bc6dda-b4ea-4774-a955-ab0aa4663168.png)
Cuando voy a actualizar los datos de un personal, sale este mensaje.

P.D.: Debería decir "Modificación exitosa." y luego hacer el _dispose_ de la ventana.

2022-08-07 22:24 UTC, leandroj1 commented
![image](https://user-images.githubusercontent.com/98528793/183313295-09bc6dda-b4ea-4774-a955-ab0aa4663168.png)
Cuando voy a actualizar los datos de un personal, sale este mensaje.

P.D.: Debería decir "Modificación exitosa." y luego hacer el _dispose_ de la ventana.

2022-08-07 22:27 UTC, leandroj1 commented
![image](https://user-images.githubusercontent.com/98528793/183313366-e95e8a2f-81bc-4baa-b429-ed9b0794612d.png)
Los campos se deberían poner como non-editable (`.setEditable(false)`) en el caso de los text fields. Para los spinners hay una función en [Utils.java](https://github.com/leandroj1/ProyectoFinalPOO/blob/134682b5287b1b21ca8913a68f8c765257fdfd19/ProyectoFinal/src/logico/Utils.java#L108) que los hace more readable.

2022-08-07 22:30 UTC, leandroj1 commented
![image](https://user-images.githubusercontent.com/98528793/183313476-f974cfbf-4e1f-45da-baea-2cb1213bdb7e.png)
Cuando voy a modificar los datos de una solicitud de personal y pongo la modalidad como "seleccione", deja que se modifique la solicitud.

Debería decir "Falta el campo de modalidad de trabajo" o algo así.

2022-08-07 23:46 UTC, leandroj1 commented
![image](https://user-images.githubusercontent.com/98528793/183315761-2c979646-2057-4de8-968a-f7bdadd8182f.png)
En modificar personal no me debería dejar modificar la cédula.

2022-08-07 23:48 UTC, leandroj1 commented
![image](https://user-images.githubusercontent.com/98528793/183315807-783a0e8e-82d5-4a84-883e-b03dfd043310.png)
Cuando voy a modificar el personal, parece que está registrando uno nuevo en lugar de modificar el puntero del objeto.

P.D.: usa _unicode_ para que no aparezcan esos caracteres.

2022-08-07 23:50 UTC, leandroj1 commented
![image](https://user-images.githubusercontent.com/98528793/183315859-e9e8ef2a-e341-4f03-ba0d-c83f64a740b0.png)
Cuando voy a ver detalles de una solicitud de personal, no carga el campo de modalidad de trabajo. Tampoco cargar en modificar.

2022-08-08 00:32 UTC, leandroj1 commented
![image](https://user-images.githubusercontent.com/98528793/183317420-67a49d19-cdc1-4c63-aa15-8620dc33d1fc.png)
No debería dejar que se modifique el nombre.

![image](https://user-images.githubusercontent.com/98528793/183317445-eb6e38d0-35cb-4dfd-8f8c-e45e3b888583.png)
Usa _unicode_ para que se ponga bien.

![image](https://user-images.githubusercontent.com/98528793/183317564-c14e4d1c-ba57-4a43-a96b-80cdb3f98371.png)
NO SE MODIFICAN LOS DATOS Y CARGA NO CARGA EL SEXO DE LA PERSONA, PONE EL VALOR "FEMENINO" POR DEFAULT

2022-08-08 14:27 UTC, leandroj1 approved these changes

2022-08-08 15:00 UTC, Brigibel12 approved these changes

2022-08-08 15:04 UTC, leandroj1 approved these changes

2022-08-08 15:23 UTC, merged